---

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: VBox

platforms:
  - name: instance-${MOLECULE_ROLE_NAME:-molecule}-1
    groups:
      - agent
      - elasticsearch
    box: centos/7
    memory: 3096
    cpus: 2
    interfaces:
      - network_name: forwarded_port
        guest: 5601
        host: 5601

provisioner:
  name: ansible
  log: true
  options:
    become: true
  group_vars:
    agent:
      agent_security_enabled: False
    elasticsearch:
      elasticsearch_security_enabled: False

verifier:
  name: ansible
